# Input files
obs_file: "data_DRB/obs_temp_flow_full"
sntemp_file: "data_DRB/sntemp_inputs_outputs_drb"
dist_matrix: "data_DRB/distance_matrix.npz"

out_dir: "output_DRB_updatedInputs_repeated_noGW"


code_dir: "river_dl"

x_vars: ["seg_rain", "seg_tave_air", "seginc_swrad", "seg_length", "seginc_potet", "seg_slope", "seg_humid", "seg_elev"]
gw_vars: ['Ar_obs','delPhi_obs','air_phi','air_amp','sin_wt','cos_wt']
primary_variable: "temp"

lambdas: [1,0]

#lambdas_gw are hyper params for weighting the rmses of Ar (amplitude ratio) and deltaPhi (phase difference)
lambdas_gw: [0, 0]


train_start_date:
  - '1985-10-01'
  - '2016-10-01'
train_end_date:
  - '2006-09-30'
  - '2020-09-30'
val_start_date: '2006-10-01'
val_end_date: '2016-09-30'
test_start_date:
  - '1980-10-01'
  - '2020-10-01'
test_end_date:
  - '1985-09-30'
  - '2021-09-30'


pt_epochs: 200
ft_epochs: 100

hidden_size: 20
